---
 - name: Install Apache Web Server
   hosts: test_servers
   become: yes

   tasks:
   - name: Install Apache Web Server
     yum: name=httpd state=installed

   - name: Start Apache Web Server
     service: name=httpd state=started enabled=yes
...
