---
- hosts: test_servers
  become: yes

  tasks:

  - name: Install Git
    yum: name=git state=latest
    when: ansible_os_family == "RedHat"

  - name: Install Git
    apt: name=git state=latest
    when: ansible_os_family == "Debian"

  - shell: git --version
    register: results

  - debug:
      var: results.stdout

  - shell: rm -fr /var/www/html/

  - name: Clone a github repository
    git:
       repo: https://github.com/ovakhnenko/ansible.git
       dest: /var/www/html
       clone: yes
       update: yes

