---
- name: Install/Enable Apache Web Server & Download/Copy index.html
  hosts: test_servers
  become: yes

  vars:
    source_html: https://raw.githubusercontent.com/ovakhnenko/ansible/main/index.html
    destin_html: /var/www/html

  tasks:

  - name: Print Ansible OS Family
    debug: var=ansible_os_family

  - name: Install Apache Web Server on RedHat
    yum: name=httpd state=latest
    when: ansible_os_family == "RedHat"

  - name: Install Apache Web Server on Debian
    apt: name=apache2 state=latest
    when: ansible_os_family == "Debian"

  - name: Download index.html to RedHat
    get_url:
      url: "{{ source_html }}"
      dest: "{{ destin_html }}"
      mode: '0644'
    notify: RestartApacheRedHat
    when: ansible_os_family == "RedHat"

  - name: Download index.html to Debian
    get_url:
      url: "{{ source_html }}"
      dest: "{{ destin_html }}"
      mode: '0644'
    notify: RestartApacheDebian
    when: ansible_os_family == "Debian"

  - name: Start Apache Web Server on RedHat
    service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Start Apache Web Server on Debian
    service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  handlers:

  - name: RestartApacheRedHat
    service: name=httpd state=restarted

  handlers:
  - name: RestartApacheDebian
    service: name=apache2 state=restarted
...
