---
- name: Install/Enable Apache Web Server & Download/Copy index.html
  hosts: test_servers
  become: yes

  vars:
    source_git: https://github.com/ovakhnenko/ansible.git
    destin_git: /var/www/repo/

    source_html: https://raw.githubusercontent.com/ovakhnenko/ansible/main/
    destin_html: /var/www/html/

    tmpl_folder: ./www/
  tasks:

  #BlockRedHat
  - block:

    - name: Install Apache Web Server on RedHat
      yum: name=httpd state=latest

    - name: Start Apache Web Server on RedHat
      service: name=httpd state=started enabled=yes

    - name: Install Git
      yum: name=git state=latest

    when: ansible_os_family == "RedHat"
  #BlockRedHat

  #BlockDebian
  - block:

    - name: Install Apache Web Server on Debian
      apt: name=apache2 state=latest

    - name: Start Apache Web Server on Debian
      service: name=apache2 state=started enabled=yes

    - name: Install Git
      apt: name=git state=latest

    when: ansible_os_family == "Debian"
  #BlockDebian

  - shell: rm -fr {{ destin_html }}

  - name: Download deadpool.jpg
    get_url:
      url: "https://raw.githubusercontent.com/ovakhnenko/ansible/main/deadpool.jpg"
      dest: "/var/www/html"
      mode: '0644'

  - name: Generate index.html
    template: src={{ tmpl_folder }}/index.j2 dest={{ destin_html }} mode=0555
#  - name: Clone a github repository
#    git:
#       repo: "{{ source_git }}"
#       dest: "{{ destin_html }}"
#       clone: yes
#       update: yes
    notify: 
       - RestartApacheRedHat
       - RestartApacheDebian
  
  handlers:

  - name: RestartApacheRedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

  - name: RestartApacheDebian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"
...

