---
- name: My Playbook
  hosts: test_servers
  become: yes

  tasks:

  - name: Delegate to Master
    shell: echo {{ inventory_hostname }} >> /home/log.txt
    delegate_to: 127.0.0.1

#  - name: Run once 
#    schell: echo Run once
#    run_once: true
#    delegate_to: linux_ubu_test

  - name: Create file 1
    copy: 
      dest: /home/file1.txt
      content:
        This is file 1
    delegate_to: linux_aml_test 

  - name: Create file 2
    copy: 
      dest: /home/file2.txt
      content:
        This is file 2
    delegate_to: linux_ubu_test 

  - shell: ls -l /home
    register: results

  - debug:
      var: results.stdout_lines

  - name: Reboot servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till my servres will come up online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      delay: 5
      timeout: 40
    delegate_to: 127.0.0.1
...
