---
# handlers file for deploy_apache_web

- name: RestartApacheRedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: RestartApacheDebian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
