---
# tasks file for deploy_apache_web

#BlockRedHat
- block:

  - name: Install Apache Web Server on RedHat
    yum: name=httpd state=latest

  - name: Start Apache Web Server on RedHat
    service: name=httpd state=started enabled=yes

  - name: Install Git
    yum: name=git state=latest

  when: ansible_os_family == "RedHat"
#BlockRedHat

#BlockDebian
- block:

  - name: Install Apache Web Server on Debian
    apt: name=apache2 state=latest

  - name: Start Apache Web Server on Debian
    service: name=apache2 state=started enabled=yes

  - name: Install Git
    apt: name=git state=latest

  when: ansible_os_family == "Debian"
#BlockDebian


- name: Download deadpool.jpg
  get_url:
    url: "{{ source_html }}/deadpool.jpg"
    dest: "{{ destin_html }}"
    mode: '0555'
  notify:
     - RestartApacheRedHat
     - RestartApacheDebian

- name: Generate index.html
  template: src=index.j2 dest={{ destin_html }}/index.html mode=0555
  notify:
     - RestartApacheRedHat
     - RestartApacheDebian
